version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.17.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "81:78:45:a5:90:c1:d3:d1:49:b2:0d:2b:95:13:29:aa"
      - checkout
      - run:
          name: Install packages `npm install`
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: "Run tests and collect coverage data"
          command: npm test -- --collectCoverage=true && npm run coverage
      - run:
          name: "Check syntax"
          command: npm run syntax
      - store_artifacts:
          path: coverage
workflows:
  version: 2
  build:
    jobs:
      - test
